name: macOS Cloudflared Tunnel with SSH & Password Change

on:
  workflow_dispatch:

jobs:
  osx-tunnel:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set runner user password (macOS)
        run: |
          echo "Changing password for user: runner"
          sudo python3 $HOME/bootstrap/kcpassword.py  "${{ secrets.RUNNER_PASSWORD }}"

      - name: Set up SSH key for runner
        run: |
          mkdir -p ~/.ssh


          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Enable SSH login
        run: |
          sudo systemsetup -setremotelogin on
          sudo dscl . -append /Groups/com.apple.access_ssh GroupMembership runner

      - name: Install cloudflared
        run: brew install cloudflared

      - name: Create cloudflared config and credentials
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARE_TOKEN }}" > ~/.cloudflared/credentials.json
          chmod 600 ~/.cloudflared/credentials.json

      - name: Start cloudflared tunnel
        run: |
          nohup cloudflared tunnel --token ${{ secrets.CLOUDFLARE_TOKEN }} run &

      - name: Keep session alive
        run: |
          echo "Tunnel is active. Tailing to prevent exit..."
          tail -f /etc/hosts
